### ISSUE TITLE
Update readme on odd path requirements and hidden files

### ISSUE THREAD

**Issue by SnijderC** [SnijderC/dyplayer#16]
Paths for combination play seem to have to be required to be named `ZH/`, as opposed to `DY/` as in the manual of the modules.

Files played by number are not corresponding to the number in the file name that, while it is suggested in the manual to number the files. It seems to be that the first file found on the drive is what is played when you ask it to play `00001`, even if that is a file in a `.Trash` directory.

**Comment by ghoeffner** [comment]
Files named x... are FIRST not LAST like you would expect! 
![image](https://user-images.githubusercontent.com/1123412/78045578-6bcaa800-7376-11ea-8622-b6679f458121.png)

**Comment by SnijderC** [comment]
Did you put that file first? Or do you have the same file in a hidden trash directory, and was it the first you saved on the module? In my experience it plays the files in order of appearance on the disk.

**Comment by ghoeffner** [comment]
It is definitely a "bug" (or intended behavior...) of the board. All files are saved to an SD card, my module does not have embedded memory. I'd probably add to the readme, that having additional files (whatever name they have...) is not recommended, because playing by ID relies on the file order and the sorting algorithm used is unknown?

**Comment by SnijderC** [comment]
I added some lines on it in the README, do you think it makes sense?
